### ISSUE TITLE
question: root level container app / main app testing

### ISSUE THREAD

**Issue by 3dd13** [palkan/engems#2]
thanks for the sharing in RailsConf and writing this up.
enjoy it and learnt a ton from you.

here a question about the engem cli usage

----------------

`bin/engem` cli currently only run tests in engines and gems.
and I am thinking of adapting the `bin/engem` and `is-dirty` to handle my root level end to end testing as well.

do you usually not having root level test case (e.g. feature / system tests) for pure engem rails project ?
wonder if you guys are moving the main_app into engines as well (like the attempt in https://cbra.info/ moving the root app into a folder called web_container)

**Comment by palkan** [comment]
> do you usually not having root level test case (e.g. feature / system tests) for pure engem rails project ?

We keep system tests at the root level (and run them without any custom CLIs, just `bundle exec rspec`).

> if you guys are moving the main_app into engines as well

I would say, eventually, yes. But at some point there could be some piece of code under the root `app/` folder, which later to be extracted into an engine. The configuration, initializers and devtools configuration (e.g., Sidekiq Web or Graphiql) still lives in the root app.

**Comment by 3dd13** [comment]
thanks for the sharing ~
