### ISSUE TITLE
table_name_prefix

### ISSUE THREAD

**Issue by gap777** [palkan/engems#5]
Hi,

I'm trying to use engem-approach, and build upon what you've already learned, in setting up a modular monolith in rails. 

I want the table names to be prefixed by the engine/subsystem name... I see `table_name_prefix` in `engines/subystem1/lib/subsystem1.rb`, but it doesn't seem to be used anywhere. Can you fill in the details on where you intended to tie that in?

Thanks

**Comment by palkan** [comment]
It's an Active Record feature: https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema.html#method-c-table_name_prefix-3D

Active Record automatically picks up it for namespaced models.

**Comment by gap777** [comment]
Right... but not working for me...

**Comment by gap777** [comment]
Do you experience it being used by migrations? Or do I need to modify the migration to also have that subsystem name / table name prefix?

**Comment by palkan** [comment]
For migrations, you need to specify prefixes separately. For example:

```ruby
class CreateUsers < ActiveRecord::Migration[7.0]
  def change
    create_table :users do
      # ...
    end
  end

  # We should preserve global table_name_prefix and table_name_suffix values (defined as `config.active_record.table_name_prefix`, etc).
  def table_name_options(config = ActiveRecord::Base)
    {
      # Use the engine's namespace here
      table_name_prefix: "#{MyEngine.table_name_prefix}#{config.table_name_prefix}",
      table_name_suffix: config.table_name_suffix
    }
  end
end
```

We usually put this into a module and include it into migrations.
